name: Python CI/CD

on:
  push:
    branches:
      - main  # Cambia según tu rama principal
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.1'  # Cambia por la versión de Python que uses

      - name: Ejecutar pruebas
        run: python -m unittest discover  # Ejecuta los tests
